Added docstrings and comments to get rooms function
zurichat/zc_plugin_dm pull request #1304
Opened 2021-10-29 22:13 UTC by mykie88

Changes effected chiefs. Thanks.

2021-10-30 17:10 UTC, man-of-mind approved these changes

2021-11-01 20:21 UTC, o4codes approved these changes
Nice work

2021-11-05 08:07 UTC, zxenonx requested changes

2021-11-05 08:07 UTC, zxenonx commented on backend/db.py
> +    It takes in two Args:
Please, quick changes for the docstring. You can follow the example below
`"""Fetches rows from a Smalltable.

    Retrieves rows pertaining to the given keys from the Table instance
    represented by table_handle.  String keys will be UTF-8 encoded.

    Args:
        table_handle: An open smalltable.Table instance.
        keys: A sequence of strings representing the key of each table
          row to fetch.  String keys will be UTF-8 encoded.
        require_all_keys: If True only rows with values set for all keys will be
          returned.

    Returns:
        A dict mapping keys to the corresponding table row data
        fetched. Each row is represented as a tuple of strings. For
        example:

        {b'Serak': ('Rigel VII', 'Preparer'),
         b'Zim': ('Irk', 'Invader'),
         b'Lrrr': ('Omicron Persei 8', 'Emperor')}

        Returned keys are always bytes.  If a key from the keys argument is
        missing from the dictionary, then that row was not found in the
        table (and require_all_keys must have been False).

    Raises:
        IOError: An error occurred accessing the smalltable.
    """`

2021-11-05 09:02 UTC, zxenonx approved these changes

2021-11-05 11:14 UTC, zxenonx approved these changes

2021-11-05 11:14 UTC, zxenonx commented
Thanks @mykie88

2021-11-05 12:26 UTC, merged