refactoring db.py, for *messages and *rooms plus Docstrings for both
zurichat/zc_plugin_dm pull request #1305
Opened 2021-10-30 15:22 UTC by Murithijoshua

* created a new helper function to reduce redundant variables
* worked on docstrings

2021-10-30 17:12 UTC, man-of-mind approved these changes

2021-10-30 18:01 UTC, o4codes requested changes
this is great work,
I'd advise the docstring for each function uses google standard as it has been adopted to be used in this project
https://google.github.io/styleguide/pyguide.html
The guideline for doc string can be found under section 2.4.4

2021-10-31 20:57 UTC, Murithijoshua commented
Thanks for the feedback, 
I will be rolling out new changes.

2021-11-01 20:19 UTC, o4codes approved these changes

2021-11-01 20:20 UTC, o4codes commented
@blacdev 
I think this is alright to be merged

2021-11-05 07:07 UTC, Murithijoshua commented on backend/db.py
> +    :rtype: class object referrencing DataStorage
this is resolved

2021-11-05 08:59 UTC, zxenonx approved these changes

2021-11-05 18:38 UTC, zxenonx approved these changes

2021-11-05 18:39 UTC, merged